### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by muriiphone** [asroboy/lapaksembako-api#1]
Halo mas, kebetulan saya lagi belajar membuat api, bolehkah saya minta database .sql nya ? terimakasi sebelumnya

**Comment by asroboy** [comment]
Hi, ini databasenya punya orang lain jadi ga bisa sy kasih langsung .sql nya, kalau mau tinggal disambungkan ke database sendiri, kemudian modif file ini "/master/src/routes.php". semuanya masih natif query, jadi kelihatan SQLnya, tinggal dipelajari.

**Comment by muriiphone** [comment]
Baik mas terimakasi, izin clone sambil belajar
